### ISSUE TITLE
When running in silent mode, write diffs to file

### ISSUE THREAD

**Issue by piersc** [rackerlabs/configsnap#1]
When running in silent mode, diffs don't happen currently. It would be useful if they instead did, but were recorded to file instead of stdout.

**Comment by reaperzn** [comment]
/usr/bin/getData -t getData-$(date +%Y-%m-%d) -p post-reboot &> getData-$(date +%Y-%m-%d)/getData/post-reboot.compare

**Comment by reaperzn** [comment]
Is this still a requirement or are we happy to do this using  shell redirection?

**Comment by reaperzn** [comment]
Closing as this is most conveniently done using shell redirection
