### ISSUE TITLE
Using -C/--compare-only doesn't include checks for http or php

### ISSUE THREAD

**Issue by JoeyPetersen** [rackerlabs/configsnap#108]
The 'is_php_detected' or 'is_apache_detected' flags aren't set when just doing a compare, so those checks don't show up in a compare-only check.

**Comment by rhodesn** [comment]
Thanks @JoeyPetersen, I've thrown something together in #109, let me know if that works for you.

**Comment by popindavibe** [comment]
@nrhodes91 I found that mysql had similar issue and pulled that thread, resulting in PR #110 
It brings a fair bit of changes on `compare_files` function, would be nice if you could review.

**Comment by popindavibe** [comment]
Closing
