### ISSUE TITLE
Python3 support plans?

### ISSUE THREAD

**Issue by dsgnr** [rackerlabs/configsnap#119]
It'd be super good for Configsnap to work with Python 3 (more specifically RHEL 8) now Python 2 is EOL.

Are there any plans to upgrade Configsnap at the moment?

**Comment by cocampbe** [comment]
LOL. I was just looking at this as well. There is a package of this in EPEL for EL8 and it wants python2. So sad.

**Comment by dsgnr** [comment]
Resolved in https://github.com/rackerlabs/configsnap/pull/120
