### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by piersc** [rackerlabs/configsnap#12]
There are existing packages called getData:
https://packages.debian.org/search?keywords=getdata
https://packages.debian.org/search?keywords=libgetdata
https://admin.fedoraproject.org/pkgdb/package/rpms/getdata/

**Comment by Beerey** [comment]
Motion to rename this project to "eiXie8je" to avoid possibility of conflicts in the future?

**Comment by piersc** [comment]
Proposed new name is "configsnap". No conflicts in Fedora or Debian pkg dbs, nothing turned up by a general search either. @Beerey , @ctria , could you confirm this is OK for you?

**Comment by ctria** [comment]
👍  (confirmed that there are no conflicts for fedora)

**Comment by Beerey** [comment]
Sounds good to me.

**Comment by piersc** [comment]
Rename is completed.
