### ISSUE TITLE
Save/compare the output of sysctl

### ISSUE THREAD

**Issue by ctria** [rackerlabs/configsnap#24]
Another setting that is lost during reboots are the kernel tunables.

We should keep/compare the output of sysctl -a

**Comment by ctria** [comment]
Update, the output is saved but not diffed between pre and post/rollback.

**Comment by piersc** [comment]
There's a number of sysctl values that are expected to vary, e.g.

```
kernel.random.boot_id = 3932b2ad-a66f-494d-bb06-94ae5240a6df
kernel.random.uuid = 18e7a73a-539e-420e-89dc-67e2cdc3ec78
kernel.osrelease = 2.6.32-573.18.1.el6.x86_64
kernel.version = #1 SMP Tue Feb 9 22:46:17 UTC 2016
talpa.intercept-filters.Cache.stats = Hits: 1031, Misses: 652223
```

I feel the downside of having false positives would outweight the benefits from diffing. What do you think?

**Comment by reaperzn** [comment]
@ctria I agree with the comment above. I am going to close this issue but if you still think there is more to be done here, re-open the issue and we can look into it.
