### ISSUE TITLE
vgcfgbackup outputting root accessible only files

### ISSUE THREAD

**Issue by garethsaxby** [rackerlabs/configsnap#28]
**Issue:** Output from vgcfgbackup is set to have permissions of 0600 by default, preventing non-root users pulling vg backup files without changing the ownership

**Code:** https://github.com/rackerlabs/configsnap/blob/master/configsnap#L233-L237

**Description:** vgcfgbackup sets a hard umask of 077, shown in the strace below, resulting in the file being only available for root when it's generated, with permissions of 0600 and ownership set to root:root

```
# strace vgcfgbackup -f /tmp/vgcfgbackup-test 2>&1 | grep -i umask
umask(077)                              = 022
```
I think this is due to [lvm2 setting it as the compile time default](https://git.fedorahosted.org/cgit/lvm2.git/tree/lib/config/defaults.h#n137).

For lifting the config settings off of the server as a non-root user, it would be nice to set the files generated to 0644, or alternatively change the file output to match the current umask settings.
Without this, it's causing issues when scp'ing the files, mandating a chmod.

This isn't an issue with configsnap itself, it's the lvm2 utils not respecting umask settings, but it would be nice to work around this limitation of the upstream tool; it's definitely easy to work around normally, but I wonder if others would also benefit from this addition.

**Comment by piersc** [comment]
You raise an interesting point. Some of the data configsnap collects is only available to the root user. This might include some things considered sensitive (list of mysql databases for example). The default behaviour of configsnap is to write everything under /root, so this wouldn't be a problem. But if you say pass "-d /tmp" then everything is visible to all users. So in actual fact we should probably be setting "workdir" to be 0600 perms. That said, I don't think there's much that configsnap collects that is only available to root, so the alternative would be to ensure configsnap doesn't collect anything that would not be available anyway to a normal user (we'd need to decide if vgcfgbackup is sensitive given those compile time defaults -- i would assume there's a reason for it).

**Comment by piersc** [comment]
No movement, closing.
