### ISSUE TITLE
Diff output back to original

### ISSUE THREAD

**Issue by popindavibe** [rackerlabs/configsnap#69]
Hello,
I know we switched to diffutils for the diff step during comparison, however I would like to suggest to bring back the old output (and subsequently revert the comment) using an extra option, `-U0`, in the `diff` subprocess call.

My main motivation for it is that the 'patch' output version of diff clearly shows which is which (filename associated to +/-).
Example:
```
--- /root/testing/configsnap/ip_addresses.pre	2018-05-20 16:53:18.752286821 +0200
+++ /root/testing/configsnap/ip_addresses.post	2018-05-20 16:57:50.281047569 +0200
@@ -11 +11 @@
-    inet 10.20.30.1/24 scope global eth0
+    inet 10.20.30.100/24 scope global eth0
```

**Comment by rhodesn** [comment]
I tend to agree that the +/- output is more useful, it's just a shame that the output includes the file path etc (IMO). It can make the output look cluttered when there are a lot differences.
