### ISSUE TITLE
Add /etc/sudoers to the file backup list

### ISSUE THREAD

**Issue by reaperzn** [rackerlabs/configsnap#71]

**Comment by StephenBrown2** [comment]
Also /etc/sudoers.d/*, since this can be included in the sudoers file for custom permissions.

**Comment by reaperzn** [comment]
@StephenBrown2 would you mind reviewing PR #72 to confirm everything works as expected

**Comment by rhodesn** [comment]
Would it be worth doing something similar to the php.d/* files where we copy to a php.d directory rather than straight into the working directory?
```python
    run.copy_file('/etc/php.ini', fail_ok=True)
    destdir = os.path.join(workdir, "php.d/")
    if not os.path.exists(destdir):
        os.makedirs(destdir)

    for filename in glob.glob('/etc/php.d/*'):
        run.copy_file(filename, destdir, fail_ok=False)
```

**Comment by StephenBrown2** [comment]
Re: `php.d` I would say so, there could be custom files in there (or just a ton, that we'd want to keep isolated)

Also, while we're on the subject of `.d` folders, Ubuntu uses an `/etc/network/interfaces.d` directory in addition to `/etc/network/interfaces` which is also on RHEL. We should probably add that dir to the backup in the case it exists.

**Comment by reaperzn** [comment]
@StephenBrown2 You make a valid point and its something we should include. I have reopened this issue but will do a new PR for the change.

**Comment by StephenBrown2** [comment]
Point. It probably should have been a separate issue, but a new PR is certainly warranted.

**Comment by reaperzn** [comment]
@StephenBrown2 I have added a new PR which uses the new copy_dir function for php.d directory and also added in a check to backup interfaces.d if it exists. Please could you test this and confirm this works. We can then close out this issue.
