### ISSUE TITLE
Network files comparison

### ISSUE THREAD

**Issue by popindavibe** [rackerlabs/configsnap#74]
I was expecting configsnap to show me a difference when modifying one of the network-related configuration files (tried with `/etc/network/interfaces`), however I realised configsnap only compare live values.

I suggest we look into implementing comparison of all network-related files as well, as a config change without a restart/ifup/ifdown would currently be left unnoticed.

**Comment by reaperzn** [comment]
@popindavibe can your review #80 to resolve this issue.
