### ISSUE TITLE
Feature request: Add --config option

### ISSUE THREAD

**Issue by reaperzn** [rackerlabs/configsnap#84]
This will allow a user to specify a custom additional.conf file which may not be in /etc/configsnap. We need to decide if this option will:
a) override the config in /etc/configsnap/additional.conf
or
b) Append to the additional.conf

**Comment by popindavibe** [comment]
I was looking for such an option when testing the last PR. 
Please note that currently the script checks and drop the load of the config file if it does not belong to the root user.
Implementing the `--config` option could be the opportunity to discuss the use to keep this extra check. The script already refuses to run as root. We could assume that the root user **should** be able to run whichever additional config file, no matter who owns it.

I personally would favour **a)** option, which is the 'natural' behaviour I would expect.

**Comment by rhodesn** [comment]
I'd second __a__ to override the additional.conf file. I also agree that we should look at reviewing the permissions requirements on the config file.

```py
 # Load custom collection list
  customcollectionfile = '/etc/configsnap/additional.conf'

...

  if os.path.exists(customcollectionfile):
      # Check file is owned by root and not read/writable by anyone else
      st = os.stat(customcollectionfile)
      if st.st_uid != 0:
          report_error("Custom collection file %s not owned by root, ignoring" %
                       customcollectionfile)
      elif oct(st.st_mode)[-2:] != '00':
          report_error("Custom collection file %s is read or writable by non-root, ignoring" %
                       customcollectionfile)
      else:
          # Only read in the config file if the above checks have passed
          Config.read(customcollectionfile)
```

**Comment by popindavibe** [comment]
A first PR has been created for this. It looks fine, and leave space for improvement (example: how do we handle comparison when the additional config file is not mentioned/present for both phases of a comparison).

**Comment by popindavibe** [comment]
Coming back to this. I am working on a new PR very similar to previous one however:
- we **keep** root use ownership mandatory on the file
- we **allow** read permissions for group and others. It is only a config file eventually, and putting passwords in the `Type=Command` section will **not** be protected by a 600 on root, as any user probing the running processes will possibly grab the full command line executed.

So the idea is more flexibility while ensuring root is the only one with write access to the configuration file.

**Comment by popindavibe** [comment]
PR #91 has been merged, closing this.

**Comment by popindavibe** [comment]
PR #91 has been merged, closing this.
